language: python

python:
  - "2.7"

env:
  global:
    - secure: "WvexIfR2nvMn77kHv4PVTiXBC9U8YkpcCbPPHr3/HWWU29t9dxerOgfNIfO0LgPYhV2yb9NJ8sLBW6/8Vs/DS8gSVnsn/IBwQXDwwcgymzkNYampq59do/56FxwFzvSk0DqJbNkmNjLzzJsdTR5mK6weN0fT50h76eUkGuLoZKM="
    - secure: "cua8Ei2rrCZBjv/7sXRcizHS3UBOQ6v1OrzOTlWuwGN7jpQQS+W/gbMnsteBh4SLnXziVzsefrcy+z4iyMnGViyXZ0InfZ82BEe/Tuu2zY8lCPMvGomNv0OUXYzMBTbf/QPNe7GezoatIrL/4Qu8/GHuOYA/I39ZDxU1iDVn9tc="

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

install:
  - sudo apt-get update
  - sudo apt-get install sshpass
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

script:
  - make deploy

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "3.2" -o $TRAVIS_BRANCH == "3.4" -o $TRAVIS_BRANCH == "3.5" -o $TRAVIS_BRANCH == "4.0" -o $TRAVIS_BRANCH == "4.2" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./manual/_book/* $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/manual/$TRAVIS_BRANCH/
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "3.2" -o $TRAVIS_BRANCH == "3.4" -o $TRAVIS_BRANCH == "3.5" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./manual_en.pdf $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/contao-manual-$TRAVIS_BRANCH.pdf
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "3.2" -o $TRAVIS_BRANCH == "3.4" -o $TRAVIS_BRANCH == "3.5" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./manual_de.pdf $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/contao-handbuch-$TRAVIS_BRANCH.pdf
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "3.2" -o $TRAVIS_BRANCH == "3.4" -o $TRAVIS_BRANCH == "3.5" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./manual_fr.pdf $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/contao-manuel-$TRAVIS_BRANCH.pdf
  - test $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "master" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./cookbook/_book/* $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/cookbook/
  - test $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "master" && sshpass -p $SCP_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./cookbook/cookbook.pdf $SCP_USER@w1.vhost.io:/home/$SCP_USER/public/books/contao-cookbook.pdf
